link:
  name: 'chassis'
  msh: 'package://pollo_description/meshes/chassis.STL'
  color: 'white'
  mass: 8
  x: -0.00074513
  y: -0.11739
  z: -1.5708
  ixx: 0.55567
  ixy: -0.00039063
  ixz: -0.0032652
  iyy: 0.57391
  iyz: -0.019683
  izz: 0.61063
  mu1: 0.7
  mu2: 0.7
  kp: 1000000
  kd: 1