link:
  name: 'LB_wheel'
  msh: 'package://asado_description/meshes/LB_wheel.STL'
  color: 'orange'
  mass: 0.8
  x: -0.032026 
  y: 2.7756E-17 
  z: 2.7756E-17
  ixx: 0.0018121
  ixy: 2.1243E-20
  ixz: 3.9097E-21
  iyy: 0.00096656
  iyz: 9.7862E-20
  izz: 0.00096656
joint:
  name: 'LB_wheel_jnt'
  child_link: 'LB_wheel'
  x: -0.27192
  y: -0.2695
  z: -0.1241
  x_axs: -1
transmission:
  name: 'LB_wheel_trans'
  jnt: 'LB_wheel_jnt'
  actuator: 'LB_wheel_actuator'
  reduction: 1