link:
  name: 'LF_wheel'
  msh: 'package://asado_description/meshes/LF_wheel.STL'
  color: 'orange'
  mass: 0.3
  x: -0.032026
  y: -1.3878E-17
  z: -5.5511E-17
  ixx: 0.0018121
  ixy: 2.1263E-22
  ixz: 1.9263E-20
  iyy: 0.00096656
  iyz: 5.0211E-21
  izz: 0.00096656
joint:
  name: 'LF_wheel_jnt'
  child_link: 'LF_wheel'
  x: -0.27192
  y: 0.1695
  z: -0.1241
  x_axs: -1
transmission:
  name: 'LF_wheel_trans'
  jnt: 'LF_wheel_jnt'
  actuator: 'LF_wheel_actuator'
  reduction: 1