link:
  name: 'RB_wheel'
  msh: 'package://asado_description/meshes/RB_wheel.STL'
  color: 'orange'
  mass: 0.8
  x: 0.032026
  y: 6.9389E-17 
  z: 0
  ixx: 0.0018121
  ixy: 3.3987E-36
  ixz: 1.3212E-20
  iyy: 0.00096656
  iyz: -4.9432E-36
  izz: 0.00096656
joint:
  name: 'RB_wheel_jnt'
  child_link: 'RB_wheel'
  x: 0.27208
  y: -0.2695
  z: -0.1241
  x_axs: -1
transmission:
  name: 'RB_wheel_trans'
  jnt: 'RB_wheel_jnt'
  actuator: 'RB_wheel_actuator'
  reduction: 1